name: Actions Workflow
#on: [push, pull_request]
on:
  push:
    branches: 
      - 'feature/*' # match: feature/<anything>, not match: feature/<anything>/<anything>
      - 'feature/**' # match: feature/<anything>, feature/<anything>/<anything>
      - '!feature/ignoreMe'
    #branches-ignore:
      #- master
    tags:
      - v1.*
    #tags-ignore:
      #- v2.*
    paths:
      - '**.java' # when ever java file is pushed will trigger this workflow
    #paths-ignore:
      #- '.github/'
  pull_request:
    types: [closed, assigned, opened, reopened]
  #schedule:
   # - cron: "0/5 * * * *" # minimum: every 5  mins (can have less), can have multiple cron setting. https://crontab.guru/
  repository_dispatch:
    types: [build]
jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Payload
        run: echo ${{ github.event.client_payload.env }}
      - name: List files before checkout #pwd result = /home/runner/work/github-action-demo/github-action-demo, this dir will not have any file from this repo. So we to clone ourselve
        run: |
          pwd 
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{ github.token }}"
          echo "So we can do manually here:" 
          echo "git clone git@github:$GITHUB_REPOSITORY"
          echo "git checkout $GITHUB_SHA"
      - name: Checkout Code #This action will clone this repo at this-push commit to current runner working dir
        uses: actions/checkout@v1 #from https://github.com/actions/checkout
      - name: List files after checkout
        run: |
          pwd 
          ls -a
      - name: Simple lib JS action #from https://github.com/actions/hello-world-javascript-action, can impl action in this repo or ref to ext
        id: greet
        uses: actions/hello-world-javascript-action@v1 #@<commit/branch(not recommended)>
        with:
          who-to-greet: Goi
      - name: Log greetieng time
        run: echo "${{steps.greet.outputs.time}}"
